# Kubernetes secrets for Nockchain mining pool
# Note: These are template values - replace with actual base64-encoded secrets

apiVersion: v1
kind: Secret
metadata:
  name: nockchain-secrets
  namespace: nockchain
type: Opaque
data:
  # Database credentials (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9ub2NrY2hhaW4=
  
  # Redis credentials
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZA==  # redispassword
  REDIS_URL: cmVkaXM6Ly86cmVkaXNwYXNzd29yZEByZWRpcy1zZXJ2aWNlOjYzNzk=
  
  # JWT secrets
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQta2V5LWhlcmU=  # your-super-secret-key-here
  JWT_REFRESH_SECRET: eW91ci1yZWZyZXNoLXNlY3JldC1rZXk=  # your-refresh-secret-key
  
  # API keys
  BLOCKCHAIN_API_KEY: eW91ci1ibG9ja2NoYWluLWFwaS1rZXk=  # your-blockchain-api-key
  
  # Email configuration
  SMTP_USER: eW91ci1lbWFpbEBnbWFpbC5jb20=  # your-email@gmail.com
  SMTP_PASS: eW91ci1hcHAtcGFzc3dvcmQ=  # your-app-password
  
  # Notification secrets
  SLACK_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvWU9VUi9TTEFDS19VUkw=
  DISCORD_WEBHOOK_URL: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvWU9VUi9ESVNDT1JEX1VSTC==
  
  # Encryption keys
  ENCRYPTION_KEY: eW91ci1lbmNyeXB0aW9uLWtleS1oZXJl  # your-encryption-key-here
  
  # Session secret
  SESSION_SECRET: eW91ci1zZXNzaW9uLXNlY3JldA==  # your-session-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: nockchain
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZ2l0aHViLXVzZXJuYW1lIiwicGFzc3dvcmQiOiJnaXRodWItdG9rZW4iLCJhdXRoIjoiWjJsMGFIVmlMWFZ6WlhKdVlXMWxPbWRwZEdoMVlpMTBiMnRsYmc9PSJ9fX0=

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: nockchain
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded TLS certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Base64 encoded TLS private key