# Next.js web application deployment for Nockchain mining pool

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nockchain-web
  namespace: nockchain
  labels:
    app: nockchain-web
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nockchain-web
  template:
    metadata:
      labels:
        app: nockchain-web
        component: frontend
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: web
          image: ghcr.io/nockchain/mining-pool:latest-web
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: nockchain-config
                  key: NODE_ENV
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nockchain-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: nockchain-secrets
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nockchain-secrets
                  key: JWT_SECRET
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: nockchain-secrets
                  key: JWT_SECRET
            - name: NEXTAUTH_URL
              value: "https://nockchain-pool.com"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: nockchain-web-service
  namespace: nockchain
  labels:
    app: nockchain-web
    component: frontend
spec:
  selector:
    app: nockchain-web
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nockchain-web-hpa
  namespace: nockchain
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nockchain-web
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nockchain-web-pdb
  namespace: nockchain
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nockchain-web