#!/bin/bash
# Lightning AI Sync Script for Nockchain Hybrid Development
# Auto-generated by Claude Code - January 18, 2025

echo "🚀 Nockchain Lightning AI Sync - Hybrid Development Workflow"
echo "============================================================"
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Not in nockchain project directory"
    echo "Please run from /Users/Patrick/nock= directory"
    exit 1
fi

# Check git status
echo "📋 Checking git status..."
git status --porcelain > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "❌ Error: Git repository not initialized"
    echo "Please initialize git first: git init"
    exit 1
fi

# Display current changes
echo "📝 Current changes:"
git status --short

# Check for uncommitted changes
if [ -n "$(git status --porcelain)" ]; then
    echo ""
    echo "💾 Adding and committing local changes..."
    git add .
    
    # Get current timestamp
    TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
    
    # Create commit message
    git commit -m "feat: local development updates - $TIMESTAMP

🚀 Generated with Claude Code
Co-Authored-By: Claude <noreply@anthropic.com>"
    
    if [ $? -eq 0 ]; then
        echo "✅ Changes committed successfully"
    else
        echo "❌ Error: Failed to commit changes"
        exit 1
    fi
else
    echo "✅ No uncommitted changes detected"
fi

# Push to remote
echo ""
echo "🔄 Pushing to GitHub remote..."
git push origin main

if [ $? -eq 0 ]; then
    echo "✅ Successfully pushed to GitHub"
    echo ""
    echo "🎯 Next Steps for Lightning AI:"
    echo "1. Open Lightning AI terminal"
    echo "2. Navigate to project directory"
    echo "3. Run: git pull origin main"
    echo "4. Run: npm install --legacy-peer-deps"
    echo "5. Run: npx turbo run build"
    echo ""
    echo "⚡ Lightning AI Sync Complete!"
else
    echo "❌ Error: Failed to push to GitHub"
    echo "Check your network connection and GitHub credentials"
    exit 1
fi